### ISSUE TITLE
Bug when trying to $include a json file containing an array with null items

### ISSUE THREAD

**Issue by ssarantidis** [boschni/json-merger#1] opened 2017-10-31 07:25 UTC
Hello, 

In the case I am trying to include a json file which contains an array with at least one **null** item, for instance _two.json_ :  

`{	
	"b": ["bb", null]
}`

into a parent file, for instance _one.json_ : 

`{
  "a": 
  {
      "aa": {"$include": "two.json"}
  }
}`

 I receive the following exception:

... \json-merger\dist\Merger.js:96
            throw new MergerError_1.default(e, this._processor.currentScope);
            ^

An error occurred while processing the property "1"
    at  path_to_one.json#/a/aa/$include/b/1

**TypeError: Cannot read property '$remove' of null**
    at Processor.processArrayItem (... \npm\node_modules\json-merger\dist\Processor.js:232:23)
    at ... \npm\node_modules\json-merger\dist\Processor.js:222:35
    at Array.forEach (<anonymous>)
    at Processor._processArray (... \npm\node_modules\json-merger\dist\Processor.js:220:16)
    at Processor.processSource (... \npm\node_modules\json-merger\dist\Processor.js:182:25)
    at Processor.processSourceProperty (... \npm\node_modules\json-merger\dist\Processor.js:173:27)
    at ... \npm\node_modules\json-merger\dist\Processor.js:209:39
    at Array.forEach (<anonymous>)
    at Processor._processObject (... \npm\node_modules\json-merger\dist\Processor.js:203:29)
    at Processor.processSource ( ... \npm\node_modules\json-merger\dist\Processor.js:179:25)

Could you please assist me on how to debug this issue?

**Comment by boschni** [comment] 2017-10-31 09:26
Hi @ssarantidis, thanks for the bug report!

The issue should be fixed now in version 0.0.25.

Please report back if the issue is resolved.

**Comment by ssarantidis** [comment] 2017-10-31 09:58
Hello @boschni , the issue seems to have been resolved. Thank you very much for your quick fix!

**Comment by boschni** [comment] 2017-10-31 15:09
No problem! Happy to help.

**Closed by boschni** 2017-10-31 15:09 UTC
